---
name: "Test multistage docker images (multi -flavours, -versions, -architectures)"

on:
  workflow_call:
    ###
    ### Variables
    ###
    inputs:
      matrix:
        description: 'The build matrix'
        required: true
        type: string
      stage:
        description: 'The stage to build (Examples: base, mods, prod or work).'
        required: true
        type: string
      artifact_prefix:
        description: 'Unique artifact name prefix (to avoid overriding existing artifcats during parallel runs).'
        required: true
        type: string
      has_refs:
        description: 'The ref build matrix as JSON string (list of git refs to build/deploy).'
        required: true
        type: boolean

jobs:
  # -----------------------------------------------------------------------------------------------
  # JOB: BUILD
  # -----------------------------------------------------------------------------------------------
  test:
    name: ${{ matrix.NAME }}-${{ matrix.VERSION }}-${{ inputs.stage }} (${{ matrix.ARCH }}) ${{ matrix.REFS }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:

      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: "[SETUP] Checkout repository (current)"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: ${{ !inputs.has_refs }}

      - name: "[SETUP] Checkout repository (ref: ${{ matrix.REFS }})"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.REFS }}
        if: ${{ inputs.has_refs }}

      - name: "[SETUP] Setup QEMU environment"
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5
          platforms: linux/amd64,linux/arm64

      - name: "[SETUP] Set artifact names"
        id: set-artifact-name
        run: |
          VERSION="${{ matrix.VERSION }}"
          ARCH="$( echo "${{ matrix.ARCH }}" | sed 's|/|-|g' )"

          NAME_CURR="${{ inputs.artifact_prefix }}-${VERSION}-${ARCH}-${{ inputs.stage }}"
          echo "curr=${NAME_CURR}" >> $GITHUB_OUTPUT


      # ------------------------------------------------------------
      # Artifact Import
      # ------------------------------------------------------------

      ###
      ### Download and import previously built image
      ###
      - name: "[Artifact Load] Download previously built image"
        uses: linuxeye/download-artifact-retry-action@master
        with:
          name: ${{ steps.set-artifact-name.outputs.curr }}

      - name: "[Artifact Load] Import previously built image"
        uses: linuxeye/shell-command-retry-action@master
        with:
          command: |
            make load INFILE=${{ steps.set-artifact-name.outputs.curr }}


      # ------------------------------------------------------------
      # Test
      # ------------------------------------------------------------
      - name: Test
        uses: linuxeye/shell-command-retry-action@master
        with:
          command: |
            make test VERSION=${{ matrix.VERSION }} STAGE=${{ inputs.stage }} FLAVOUR=${{ matrix.FLAVOUR }} ARCH=${{ matrix.ARCH }}
