name: Lint

on:
  workflow_call:

jobs:

  # -----------------------------------------------------------------------------------------------
  # JOB (1/1): Lint
  # -----------------------------------------------------------------------------------------------
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: "[SETUP] Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Files
        uses: linuxeye/shell-command-retry-action@master
        with:
          command: |
            make lint-files

      - name: Lint Yaml
        uses: linuxeye/shell-command-retry-action@master
        with:
          command: |
            make lint-yaml

      - name: Lint JSON
        uses: linuxeye/shell-command-retry-action@master
        with:
          command: |
            make lint-json

      - name: Lint Bash
        uses: linuxeye/shell-command-retry-action@master
        with:
          command: |
            make lint-bash
